tolgee/tolgee-platform

- backend/app/src/main/kotlin/io/tolgee/api/v2/controllers/translation/V2TranslationsController.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/translations/v2TranslationsController/V2TranslationsControllerFilterTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/translations/v2TranslationsController/V2TranslationsControllerViewTest.kt
- backend/app/src/test/kotlin/io/tolgee/service/query_builders/CursorUtilUnitTest.kt
- backend/data/src/main/kotlin/io/tolgee/development/testDataBuilder/data/TranslationsTestData.kt
- backend/data/src/main/kotlin/io/tolgee/service/query_builders/CursorUtil.kt
- backend/data/src/main/kotlin/io/tolgee/service/query_builders/TranslationsViewBuilder.kt
When no sorting was specified, Tolgee defaulted to sorting by `keyId` and `keyName`. However, the returned cursor only specified `keyId` and this caused subsequent requests to not use the same sorting method. This patch fixes it by only using `keyId` when no sort is specified.
Regression test included.
closes #1345
> fix: consistent sorting when sort is unspecified

- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2KeyController/V2KeyInNamespaceControllerTest.kt
- backend/data/src/main/kotlin/io/tolgee/dtos/request/key/ComplexEditKeyDto.kt
This PR fixes #1520 by implementing `setJsonNamespace` function on the `ComplexEditKeyDto` (the same as in `EditKeyDto` and `CreateKeyDto`).
> fix: Check for empty namespace in complex-update endpoint

- e2e/cypress/common/translations.ts
- e2e/cypress/e2e/translations/with5translations/withViews.cy.ts
- e2e/cypress/support/dataCyType.d.ts
- webapp/src/component/editor/Editor.tsx
- webapp/src/component/key/KeyTemplate.tsx
- webapp/src/component/key/SvgKeys.tsx
- webapp/src/fixtures/shortcuts.tsx
- webapp/src/views/projects/translations/TranslationOpened.tsx
- webapp/src/views/projects/translations/TranslationsList/CellTranslation.tsx
- webapp/src/views/projects/translations/TranslationsShortcuts.tsx
- webapp/src/views/projects/translations/TranslationsTable/CellTranslation.tsx
- webapp/src/views/projects/translations/cell/ControlsEditor.tsx
- webapp/src/views/projects/translations/context/TranslationsContext.ts
- webapp/src/views/projects/translations/context/services/useTranslationsService.tsx
- webapp/src/views/projects/translations/context/shortcuts/useTranslationsShortcuts.ts
- webapp/src/views/projects/translations/useEditableRow.ts
This PR adds "Insert source" button to the editor to translation fields.
Translators can now click this button (or use the `Ctrl + Ins` keyboard shortcut) to insert the source text into the translation field. If the source language is not currently displayed, it gets the source text from API.
> feat: Editor -> "Insert source" button

- backend/data/src/main/kotlin/io/tolgee/util/WordCounter.kt
- backend/data/src/test/kotlin/io/tolgee/util/WordCounterTest.kt
I was thrilled to see the usage of BreakIterator and the word counting was more robust than I realized! However, these changes should greatly improve the performance (if it's slow) by pre-compiling the regexes and not having allocate memory for lists of words that aren't actually used. 
I added one test case- my question is if we should really count ICU variables and HTML tags. I think ideally, when you're paying a translator, they "preserve" these tags and don't "translate" them. But I guess that's subjective and the current implementation is more conservative (since it represents work done to preserve those variables and tags in the new translation).
> Word count performance improvements

- webapp/src/views/userSettings/accountSecurity/EnableMfaDialog.tsx
This PR fixes double ending brackets in the generated OTP. This change is only visual and only changes how the account is displayed in the authenticator app for newly generated OTPs.
When user has email address `example@domain.com`, the generated OTP name will become `Tolgee (example@domain.com)`.
After that, the OTP name is URI-encoded, but then another ending bracket is added, so the full OTP name is `Tolgee (example@domain.com))`.
> fix: OTP name contains double ending brackets

- backend/app/build.gradle
- settings.gradle
This is a follow on to PR #1614 and issue #1271 
One of the primary motivations for moving to AWS SDK v2 was to gain flexible and secure ways of authenticating, including STS Web Tokens. However, this method is not tried if the STS dependency is not on the app classpath. This PR adds the dependency to the build.
FYI @kenske
> Add STS dependency so that web identity token authentication works

- webapp/src/component/security/OAuthService.tsx
Currently, if you use an authorization url such as `https://auth.example.com/oauth2/auth?foo=bar`, then the generated url when authenticating becomes `https://auth.example.com/oauth2/auth?foo=bar?client_id=...` instead of `https://auth.example.com/oauth2/auth?foo=bar&client_id=...`. By using the browsers URL api, we can let it figure that out and we can set the parameters on top of it. In addition, the `toString()` call on `URL` will also ensure the url is encoded, so the `encodeURI` method call is no longer necessary.
Some things to note as a result of this change:
* The spaces `scope` parameter will now be encoded as `%20` rather than a `+`. But in general, the `%20` is the safer option and is covered by the RFC spec.
* Each of the query params will now be properly url encoded, so if …
> fix(oauth2): generate valid auth url when auth url already contains query params

- docker/app/Dockerfile
It would be nice if the docker container get a healthcheck.
Currently it is hard set to Port 8080. The Problem is that it can change through env and config, but I don't know how to get the port from the config file without installing something like [yq](https://github.com/mikefarah/yq).
> fix: Add healthcheck to dockerfile

- backend/data/src/main/kotlin/io/tolgee/service/dataImport/processors/ProcessorFactory.kt
- backend/data/src/main/kotlin/io/tolgee/service/dataImport/processors/PropertyFileProcessor.kt
- backend/data/src/test/kotlin/io/tolgee/unit/service/dataImport/processors/processors/PropertiesParserTest.kt
- backend/data/src/test/resources/import/example.properties
- webapp/src/i18n/cs.json
- webapp/src/i18n/da.json
- webapp/src/i18n/de.json
- webapp/src/i18n/en.json
- webapp/src/i18n/es.json
- webapp/src/i18n/fr.json
- webapp/src/i18n/pt.json
- webapp/src/i18n/ro.json
- webapp/src/i18n/zh.json
- webapp/src/views/projects/import/component/ImportFileInput.tsx
> feat: Add simple properties file importer

- backend/data/src/main/kotlin/io/tolgee/model/dataImport/ImportTranslation.kt
- backend/data/src/main/resources/db/changelog/schema.xml
It was throwing 500 with ConstraintViolationException, because we are soft deleting the import and Liquibase update added strict unique key constraint for import translations -> translation conflict OneToOne relations. Moving to OneToMany with dropping the unique key should resolve this.
> fix: Import ConstraintViolationException

- backend/data/src/main/kotlin/io/tolgee/formats/android/AndroidParsingConstants.kt
- backend/data/src/main/kotlin/io/tolgee/formats/android/out/TextToAndroidXmlConvertor.kt
- backend/data/src/test/kotlin/io/tolgee/unit/formats/android/out/TextToAndroidXmlConvertorTest.kt
This PR fixes 
- String not wrapped with CDATA when contains content which is not parseable with XML parser
-  Sequences  with multiple`\n` are quoted, while this is unnecessary
- UTF 8 escaped characters are not re-escaped with `\` anymore
> fix: Android Import/Export fixes

- backend/api/src/main/kotlin/io/tolgee/security/thirdParty/GoogleOAuthDelegate.kt
- backend/data/src/main/kotlin/io/tolgee/configuration/tolgee/GoogleAuthenticationProperties.kt
Enhanced the authentication logic to support a comma-separated list of Google Workspace domains in `googleConfigurationProperties.workspaceDomain`.
This feature would be useful in my case. I have opened a PR and if you think that this benefits the project, you are welcome to merge it.
Disclaimers:
- I have never used Kotlin
- I don't know if this even builds
If you require any improvements or changes to keep up with the project's standards don't hesitate to let me know but my experience in this stack is very limited
> feat: Allow multiple Google Workspace domains for user authentication

- backend/app/src/test/kotlin/io/tolgee/activity/ActivityLogTest.kt
- backend/data/src/main/kotlin/io/tolgee/activity/EntityDescriptionProvider.kt
- backend/data/src/main/kotlin/io/tolgee/activity/projectActivityView/ActivityViewByRevisionsProvider.kt
When the entity was hibernate proxy, the `EntityDescriptionProvider` wasn't able to get `ActivityEntityDescribingPaths` annotation and so it didn't store all activity relations. This PR fixes it.
> fix: Activity relation storing

- backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/slack/SlackEventsController.kt
- backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/slack/SlackSlashCommandController.kt
- backend/app/src/test/kotlin/io/tolgee/service/slack/SlackConfigServiceTest.kt
- backend/app/src/test/kotlin/io/tolgee/slack/SlackIntegrationTest.kt
- backend/data/src/main/kotlin/io/tolgee/component/automations/processors/slackIntegration/SlackErrorProvider.kt
- backend/data/src/main/kotlin/io/tolgee/component/automations/processors/slackIntegration/SlackExecutor.kt
- backend/data/src/main/kotlin/io/tolgee/component/automations/processors/slackIntegration/SlackExecutorHelper.kt
- backend/data/src/main/kotlin/io/tolgee/component/automations/processors/slackIntegration/SlackHelpBlocksProvider.kt
- backend/data/src/main/kotlin/io/tolgee/development/testDataBuilder/data/SlackTestData.kt
- backend/data/src/main/kotlin/io/tolgee/dtos/slackintegration/SlackConfigDto.kt
- backend/data/src/main/kotlin/io/tolgee/service/slackIntegration/SavedSlackMessageService.kt
- backend/data/src/main/kotlin/io/tolgee/service/slackIntegration/SlackConfigService.kt
- backend/data/src/main/resources/I18n_en.properties
What I have done:
- Rename all translation keys (i18n) according to the Tolgee guide.
- Refresh message design.
- Redesign the /help message.
- Now, users can set whether the subscription is global or not.
> fix: new updates

- backend/data/src/main/kotlin/io/tolgee/batch/processors/PreTranslationByTmChunkProcessor.kt
The production database is being overwhelmed by the TM translation jobs, which have unlimited per job concurrency. It doesn't seem any beneficial. In this PR i limited one parallel TM execution per batch job.
> fix: Make batch MT translation less concurrent

- backend/data/src/main/resources/I18n_en.properties
- ee/backend/app/src/main/kotlin/io/tolgee/ee/api/v2/controllers/slack/SlackSlashCommandController.kt
- ee/backend/app/src/main/kotlin/io/tolgee/ee/component/slackIntegration/SlackErrorProvider.kt
- ee/backend/app/src/main/kotlin/io/tolgee/ee/component/slackIntegration/SlackExecutor.kt
- ee/backend/app/src/main/kotlin/io/tolgee/ee/component/slackIntegration/SlackExecutorHelper.kt
- ee/backend/app/src/main/kotlin/io/tolgee/ee/service/slackIntegration/SlackConfigPreferenceService.kt
- ee/backend/app/src/main/kotlin/io/tolgee/ee/service/slackIntegration/SlackConfigService.kt
- ee/backend/tests/src/test/kotlin/io/tolgee/ee/service/slack/SlackConfigServiceTest.kt
- ee/backend/tests/src/test/kotlin/io/tolgee/ee/slack/SlackIntegrationTest.kt
- changing the method of obtaining the alias of an authorized Slack user
- The user can now unsubscribe from the specified language (/tolgee unsubscribe 1 cs)
- add new scopes to request
- fixed a bug where changes were not updated if the base language was changed first.
> feat: slack integration improvements

- .github/ISSUE_TEMPLATE/bug_report.md
Fixes two issues:
- Versions and environment is not rendered as bold
- Typo in the word `environment`
> issue-template: Fix bug report issue template formatting and typo

- backend/api/build.gradle
- backend/app/build.gradle
- backend/data/build.gradle
- backend/development/build.gradle
- backend/security/build.gradle
- backend/testing/build.gradle
- ee/backend/app/build.gradle
- ee/backend/tests/build.gradle
- gradle.properties
I've investigated tests performance with AuthTest as the test subject.
* Spring context starts in under 3 seconds on my machine (Mac 3 Pro), which is alright.
* Gradle build takes about 15 seconds each time. I would expect less then 3 seconds on subsequent runs.
* Gradle configuration phase takes around 3 sec, from which 90% takes Sentry.
* `dependencyResolution` phase took 4-7 seconds. I've fixed it around 1 sec with https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/222#issuecomment-411005109
* Task `kaptTestKotlin` takes at least 1.5 seconds and misses cache every time. Consider upgrade to KSP and to Kotlin 2.0. I excluded `build-info.properties` that causes cache miss through Gradle Cache normalization, but exclusion doesn't seem to work consistently. Is …
> chore: integration tests performance fixes

- backend/app/src/main/kotlin/io/tolgee/ExceptionHandlers.kt
It was throwing 500 when static resource was not found. (Usually favicon.ico)
> fix: No static resource found error handling

- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2KeyController/KeyControllerResolvableImportAutomationsTest.kt
- backend/data/src/main/kotlin/io/tolgee/development/testDataBuilder/data/ResolvableImportTestData.kt
- backend/data/src/main/kotlin/io/tolgee/repository/TranslationRepository.kt
- backend/data/src/main/kotlin/io/tolgee/service/key/ResolvingKeyImporter.kt
- backend/data/src/main/kotlin/io/tolgee/service/translation/TranslationService.kt
- Update the translation state when the base is changed upon import from Figma.
- Test the new behavior.
Also, I discovered that there is no problem with autotranslation of keys upon Figma imports.
> fix: Set outdated flag in resolvable import

- backend/data/src/main/kotlin/io/tolgee/repository/ApiKeyRepository.kt
> fix: only show api keys from non-deleted projects

- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2KeyController/KeyControllerResolvableImportTest.kt
- backend/data/src/main/kotlin/io/tolgee/dtos/request/translation/importKeysResolvable/ImportTranslationResolution.kt
- backend/data/src/main/kotlin/io/tolgee/dtos/request/translation/importKeysResolvable/ImportTranslationResolvableDto.kt
- backend/data/src/main/kotlin/io/tolgee/service/key/ResolvingKeyImporter.kt
I added new option `force-override` to import resolvable endpoint. It should forcefully update/create/keeps the translation to the new value. Also I wrote unit test.
> feat: import resolvable force override

- backend/data/src/main/kotlin/io/tolgee/service/dataImport/ImportService.kt
> fix: Respect project.icuPlaceholders in singleStepImport

- README.md
Hey @JanCizmar @stepan662 
Fix typo of `Hacktobefest.md` to `Hacktoberfest.md` so that it points to correct file
> Fix typo of Hacktoberfest.md so that it points to correct file

- CONTRIBUTING.md
- DEVELOPMENT.md
- README.md
- e2e/README.md
Hi guys,
I was heaving a creative mind on Sunday, so I created pages for setting up the development environment right in the code, instead of wiki, to be easily editable by everyone and openable also from IDE.
It also adds the play-buttons to the scripts and run configurations in Idea to be clickable:
Have a nice day!
> chore: Local development setup in readme's

- backend/data/build.gradle
* We are now depending on `spring-boot-starter-test` and its transitive dependency on `org.json` which is from some strange "Android Vaadin" lib.
* Depend on the test lib only in tests.
* Use the `org.json` package from Mailjet which uses it as an interface.
> chore: Do not depend on Spring test library as implementation in backend

- backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/ConfigurationController.kt
- backend/api/src/main/kotlin/io/tolgee/configuration/PublicConfigurationDTO.kt
- backend/data/src/main/kotlin/io/tolgee/component/contentDelivery/ContentDeliveryFileStorageProvider.kt
- backend/data/src/main/kotlin/io/tolgee/configuration/tolgee/ContentDeliveryProperties.kt
- Checks storage is configured to show CD options in the UI
- Noted that CD storage needs to be configured in the docs
> fix: Content delivery configured check & docs

- build.gradle
Instead of running multiple gradle jobs sequentially
> chore: Make the default `gradle test` passing

- docker/app/Dockerfile
We use `wget` because `curl` is not installed on the image.
Originally developed by @vexdev in #2676, thank you for that!
Closes #2675.
> fix: Healthcheck of docker image

- backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/batch/V2ExportController.kt
`/export` is now used for both, operation and tag.
Proper fix for tolgee/documentation#756.
> chore: Fix slug conflict in docs

- build.gradle
When a developer has a running stack on their machine on the standard port 8080, running the `diffChangeLog` task fails because of a port conflict.
This change uses another port which should be free on most machines in most cases.
> Use an unlikely-to-be-used port when updating changelog

- backend/data/src/main/kotlin/io/tolgee/formats/ImportFileProcessor.kt
Namespaces are allowed to contain dots (`.`). Exporting projects with such namespaces will result in directories for namespaces containing dots. The current implementation assumes the first dot-separated section to be language and guesses the language incorrectly.
> fix: use file name instead of whole path for language guess

- backend/app/src/test/kotlin/io/tolgee/AuthTest.kt
- backend/app/src/test/kotlin/io/tolgee/StartupImportCommandLineRunnerTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/SlugControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/V2InvitationControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/V2LanguageControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ImportController/V2ImportControllerAddFilesTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ProjectsController/ProjectsControllerCreateTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ProjectsController/ProjectsControllerEditTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ProjectsController/ProjectsControllerInvitationTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ProjectsController/ProjectsControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ScreenshotController/SecuredKeyScreenshotControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/controllers/ExportControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/controllers/PublicControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/controllers/internal/SqlControllerTest.kt
- backend/app/src/test/kotlin/io/tolgee/repository/ProjectRepositoryTest.kt
- backend/app/src/test/kotlin/io/tolgee/repository/dataImport/ImportFileRepositoryTest.kt
- backend/app/src/test/kotlin/io/tolgee/repository/dataImport/ImportRepositoryTest.kt
- backend/app/src/test/kotlin/io/tolgee/security/DenyInternalTest.kt
- backend/app/src/test/kotlin/io/tolgee/security/ProjectApiKeyAuthenticationTest.kt
- backend/app/src/test/kotlin/io/tolgee/security/ProjectPermissionFilterTest.kt
- backend/app/src/test/kotlin/io/tolgee/service/TranslationServiceTest.kt
- backend/app/src/test/kotlin/io/tolgee/service/project/ProjectServiceTest.kt
- backend/data/src/main/kotlin/io/tolgee/development/DbPopulatorReal.kt
- backend/testing/src/main/kotlin/io/tolgee/fixtures/ProjectAuthRequestPerformer.kt
The functionality of creating a base project with a particular name is not used anywhere. It can be replaced by creating a base project with UUID as a name for readability.
> chore: Create test base project with random UUID by default

- webapp/src/views/projects/project/ProjectSettingsGeneral.tsx
The current layout of settings pushes the form below the project avatar when a validation failure occurs.
This PR alters the layout which fixes the form position.
> chore: Reorganization of settings for correct error display

- backend/data/src/main/kotlin/io/tolgee/service/dataImport/CoreImportFilesProcessor.kt
- backend/data/src/main/kotlin/io/tolgee/service/dataImport/ImportDataManager.kt
This fixes poor performance when the "Create new keys" option is disabled, and many keys are to be imported.
> fix: import - create new keys - use cached existing keys

- .github/workflows/test.yml
Nowadays, all the actions need to be defined in GitHub UI to enable auto-merge.
This change adds an arbitrary `Everything passed` action dependent on all other, therefore it is the only one which needs to be defined to pass.
> chore: Add everything passed action for easier auto-merge conditions

- .github/workflows/test.yml
When some jobs not succeed, the `Everything passed` job gets skipped which is taken as a success by github actions.
This change checks the statuses of the dependent jobs, making the last check failing if something before fails.
> chore: Check statuses of dependent jobs before merge

- .editorconfig
Nowadays, our IDEAs may not be consistent and may cause conflicts in imports.
This PR sets the limit to a fixed number to be followed across IDEs.
> chore: Define limit of wildcard imports in the editorconfig file

- .run/E2E tests.run.xml
- .run/Frontend for E2E tests.run.xml
To make it possible to run also FE for E2E tests and open the Cypress window, directly from IDEA.
> chore: Add run configurations for E2E tests

- backend/api/src/main/kotlin/io/tolgee/websocket/WebSocketConfig.kt
To make it consistent with the other auth for `projects`.
> chore: Websockets auth for `users` instead of `user`

- e2e/cypress/e2e/userSettings/userSettings.cy.ts
It was failing in the builds a lot when the loading took more than the static 50 ms. This change waits for the element to be visible therefore making it more stable.
> chore: Making intermittent test stable

- .github/workflows/inactive-issues.yml
- .github/workflows/prerelease-alpha.yml
- .github/workflows/preview.yml
- .github/workflows/release.yml
- .github/workflows/reportIntermittentTests.yml
- .github/workflows/test.yml
GitHub will use it as default for ubuntu-latest, therefore we should be compatible.
> Run explicitly on Ubuntu 24.04

- e2e/cypress/e2e/userSettings/userSettings.cy.ts
`getAnyContainingText` probably sometimes selects a different element in the page.
This PR unifies it with the other tests in the suite which passes on localhost consistently.
> chore: Fix clicking on `Project API keys`

- e2e/cypress/support/registerCommands.ts
Calling `findDcy`, `nextUntilDcy` and `findInputByName` was calling the `.find('[data-cy="${dataCy}"]')` function on a jQuery object, therefore disabling the Cypress native retry functionality.
This change wraps the jQuery object into a Cypress object which enables the retry-timeout functionality waiting for the state to be correct.
> chore: Add retry logic to custom commands

- backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/batch/ExportApiResponse.kt
- backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/batch/V2ExportController.kt
> fix: OpenApi docs for exporting endpoints

- webapp/src/index.tsx
Thank you for releasing the Japanese translation.
In v3.103.0, Japanese is selectable, but it is not displayed. 
From my understanding, I think that the static data for i18n included in this pull request needs to be loaded.
ref: https://github.com/tolgee/tolgee-platform/pull/2932
> Fix Japanese static data load

- backend/data/src/main/kotlin/io/tolgee/formats/xmlResources/out/TextToXmlResourcesConvertor.kt
- backend/data/src/test/kotlin/io/tolgee/unit/formats/android/out/TextToAndroidXmlConvertorTest.kt
- backend/data/src/test/kotlin/io/tolgee/unit/formats/compose/out/TextToComposeXmlConvertorTest.kt
- Add fallback when XML parsing fails, assume the text is single XML text node
- Add tests for handling malformed XML in Android and Compose converters
Fixes #2967
> fix: add XML parsing error fallback
