webapp/src/views/organizations/components/UserOrganizationSettingsSubtitleLink.tsx

fix(UserSettings): fix user settings profile switch

fix(UserSettings): fix

---

e2e/cypress/integration/projects/integrate.ts
webapp/src/views/projects/integrate/guides/Angular.mdx
webapp/src/views/projects/integrate/guides/Gatsby.mdx
webapp/src/views/projects/integrate/guides/Js.mdx
webapp/src/views/projects/integrate/guides/Next.mdx
webapp/src/views/projects/integrate/guides/React.mdx
webapp/src/views/projects/integrate/guides/Svelte.mdx
webapp/src/views/projects/integrate/guides/Vue.mdx

Connected to: https://github.com/tolgee/tolgee-js/pull/2393

fix: update docs when ui is auto included

---

backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/V2ExportControllerTest.kt
backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ImportController/V2ImportControllerResultTest.kt
backend/app/src/test/kotlin/io/tolgee/service/export/exporters/JsonFileExporterTest.kt
backend/app/src/test/kotlin/io/tolgee/service/export/exporters/XliffFileExporterTest.kt
backend/data/src/main/kotlin/io/tolgee/service/dataImport/CoreImportFilesProcessor.kt
backend/data/src/main/kotlin/io/tolgee/service/dataImport/ImportService.kt
backend/data/src/main/kotlin/io/tolgee/service/dataImport/RemoveExpiredImportService.kt
backend/data/src/main/kotlin/io/tolgee/service/dataImport/processors/ZipTypeProcessor.kt
backend/data/src/main/kotlin/io/tolgee/service/export/exporters/FileExporter.kt

- Fix: When import expired, cannot import anything else
- Fix: When export zip files start by slash language is not recognized

fix: Fix import issues. Closes #1069

---

backend/app/src/test/kotlin/io/tolgee/service/LanguageServiceTest.kt
backend/app/src/test/kotlin/io/tolgee/service/TranslationServiceTest.kt
backend/data/src/main/kotlin/io/tolgee/development/testDataBuilder/data/TranslationCommentsTestData.kt
backend/data/src/main/kotlin/io/tolgee/service/TranslationService.kt

- Cannot delete language when translation comment exists
- Auto translated state not dismissed when set empty translation

fix: Fix minor bugs

---

backend/app/src/main/kotlin/io/tolgee/api/v2/controllers/V2InvitationController.kt
backend/app/src/main/kotlin/io/tolgee/security/controllers/InvitationController.kt
backend/data/src/main/kotlin/io/tolgee/service/InvitationService.kt
webapp/src/service/SecurityService.tsx
webapp/src/service/SignUpService.tsx

- Fixed sign up with expired invitation in local storage
- Fixed login with expired invitation in local storage

fix: Invitation bugs

---

backend/app/src/main/kotlin/io/tolgee/api/v2/controllers/TranslationSuggestionController.kt
backend/app/src/main/kotlin/io/tolgee/api/v2/controllers/V2KeyController.kt
backend/app/src/main/kotlin/io/tolgee/controllers/KeyController.kt
backend/app/src/main/resources/application.yaml
backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2KeyController/V2KeyControllerDeleteManyKeysTest.kt
backend/app/src/test/resources/application.yaml
backend/data/src/main/kotlin/io/tolgee/activity/data/ActivityType.kt
backend/data/src/main/kotlin/io/tolgee/model/StandardAuditModel.kt
backend/data/src/main/kotlin/io/tolgee/model/key/Key.kt
backend/data/src/main/kotlin/io/tolgee/model/translation/Translation.kt
backend/data/src/main/kotlin/io/tolgee/repository/KeyRepository.kt
backend/data/src/main/kotlin/io/tolgee/repository/TranslationRepository.kt
backend/data/src/main/kotlin/io/tolgee/service/KeyService.kt
backend/data/src/main/kotlin/io/tolgee/service/machineTranslation/MtService.kt
backend/data/src/main/resources/db/changelog/schema.xml
webapp/src/views/projects/translations/TranslationTools/MachineTranslation.tsx

- Faster key delete
- Larger hibernate batch + larger sequence allocation size
- Suggestion controller always returns null when base language is empty or blank

fix: Minor fixes

---

README.md

Announcing rewards for Tolgee contributors

docs: Added rewards to the readme

---

webapp/src/component/searchSelect/SearchSelectMulti.tsx
webapp/src/views/projects/translations/Tags/TagInput.tsx

fix(ui): case insensitive autocomplete (#1670)

---

webapp/src/views/projects/translations/TranslationsShortcuts.tsx
webapp/src/views/projects/translations/cell/ControlsEditor.tsx
webapp/src/views/projects/translations/context/services/useTranslationsService.tsx
webapp/src/views/projects/translations/useEditableRow.ts

This PR adds checks for displaying "Insert base text" only if the user has permission to view the base language texts.

feat: Check for view permission to display "Insert base text"

---

backend/data/src/main/kotlin/io/tolgee/service/query_builders/translationViewBuilder/QueryBase.kt

Reverts tolgee/tolgee-platform#1738

fix: Unresolved comments filtering issues

---

backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/batch/BatchJobManagementController.kt
backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/batch/StartBatchJobController.kt
backend/api/src/main/kotlin/io/tolgee/hateoas/batch/BatchJobModel.kt
backend/api/src/main/kotlin/io/tolgee/hateoas/batch/BatchJobModelAssembler.kt
backend/api/src/main/kotlin/io/tolgee/websocket/ActivityWebsocketListener.kt
backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/batch/BatchJobManagementControllerTest.kt
backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/batch/StartBatchJobControllerTest.kt
backend/data/src/main/kotlin/io/tolgee/batch/BatchJobService.kt
backend/data/src/main/kotlin/io/tolgee/model/batch/BatchJob.kt
backend/data/src/main/kotlin/io/tolgee/model/batch/BatchJobStatus.kt
backend/data/src/main/kotlin/io/tolgee/repository/BatchJobRepository.kt
backend/data/src/main/kotlin/io/tolgee/websocket/WebsocketEvent.kt
backend/data/src/main/resources/db/changelog/schema.xml

feat: Add clever endpoint & String enum types & operations > post requests

---

backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/V2ProjectsController.kt

Make /v2/projects API accessible via PAT

---

webapp/src/component/MdxProvider.tsx
webapp/src/views/projects/integrate/IntegrateView.tsx
webapp/src/views/projects/integrate/guides.tsx
webapp/src/views/projects/integrate/guides/Cli.mdx

feat: add tolgee CLI to integration section + fix overflow

---

backend/data/src/main/kotlin/io/tolgee/configuration/tolgee/ImportProperties.kt

describe how the folder structur should look like to import a project

update import.dir description

---

backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/ApiKeyController.kt
backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/translation/TranslationsController.kt
backend/api/src/main/kotlin/io/tolgee/facade/ProjectWithStatsFacade.kt
backend/app/src/test/kotlin/io/tolgee/StreamingBodyDatabasePoolHealthTest.kt
backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/ApiKeyControllerTest.kt
backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/V2ExportControllerTest.kt
backend/data/build.gradle
backend/data/src/main/kotlin/io/tolgee/component/OutdatedFlagListener.kt
backend/data/src/main/kotlin/io/tolgee/model/ApiKey.kt
backend/data/src/main/kotlin/io/tolgee/service/security/ApiKeyService.kt
e2e/cypress/common/apiCalls/testData/testData.ts
e2e/cypress/e2e/projects/permissions/permissionsServerAdmin.1.cy.ts
e2e/cypress/e2e/projects/projectDashboard.cy.ts
e2e/cypress/e2e/projects/projectsListDashboard.cy.ts
gradle.properties
webapp/vite.config.ts

- In this PR I also upgraded Hiberante to 6.4
- The issue possibly affected all entities
- No sure whether this is a bug in hibernate, but it looks like it's being fixed by removing the build time enhancement properties

fix: API Key regeneration

---

backend/data/src/main/kotlin/io/tolgee/dtos/request/translation/TranslationFilters.kt

Closes [#2229](https://github.com/tolgee/tolgee-platform/issues/2229)

fix: improve translation filters API docs

---

backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/translation/TranslationsController.kt

fix: API docs -> set translations operation

---

backend/data/src/main/kotlin/io/tolgee/model/enums/announcement/Announcement.kt
webapp/src/component/layout/TopBanner/useAnnouncement.tsx
webapp/src/constants/GlobalValidationSchema.tsx
webapp/src/service/apiSchema.generated.ts

Waiting for https://github.com/tolgee/documentation/pull/595

feat: tolgee cli 2 announcement

---

backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/dataImport/StreamingImportProgressUtil.kt
backend/app/src/main/resources/application.yaml
backend/data/src/main/kotlin/io/tolgee/service/dataImport/status/ImportApplicationStatus.kt
webapp/src/views/projects/import/hooks/useApplyImportHelper.tsx

- Extend default async request timeout
- Add error message when import times out

fix: Import timeout issues

---

backend/data/src/main/kotlin/io/tolgee/dtos/cacheable/UserAccountDto.kt
backend/data/src/main/kotlin/io/tolgee/service/EmailVerificationService.kt

It fails, when redis cache is used.

fix: Remove EmailVerification entity from UserAccountDto

---

backend/data/src/main/kotlin/io/tolgee/configuration/CustomPrettyPrinterConfiguration.kt
backend/data/src/main/kotlin/io/tolgee/formats/genericStructuredFile/out/CustomPrettyPrinter.kt
backend/data/src/main/kotlin/io/tolgee/formats/genericStructuredFile/out/GenericStructuredFileExporter.kt
backend/data/src/main/kotlin/io/tolgee/formats/json/out/JsonFileExporter.kt
backend/data/src/main/kotlin/io/tolgee/formats/yaml/out/YamlFileExporter.kt
backend/data/src/main/kotlin/io/tolgee/service/export/FileExporterFactory.kt
backend/data/src/test/kotlin/io/tolgee/unit/formats/json/out/JsonFileExporterTest.kt
backend/data/src/test/kotlin/io/tolgee/unit/formats/yaml/out/YamlExportTestData.kt

remove a space before the colon at json format.

feat: more common json formatting

---

Hacktobefest2024.md

Made some small change will enhence the quilty of reading

docs: Update Hacktobefest2024.md

---

backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/ProjectActivityControllerTest.kt
backend/data/src/main/kotlin/io/tolgee/activity/ActivityService.kt
backend/data/src/main/kotlin/io/tolgee/development/testDataBuilder/data/dataImport/ImportTestData.kt
backend/data/src/main/kotlin/io/tolgee/repository/activity/ActivityRevisionRepository.kt
webapp/src/component/activity/ActivityTitle.tsx

- do not show activities with an empty list of modified entities

fix: activity label zero keys

---

backend/data/src/main/kotlin/io/tolgee/formats/android/out/TextToAndroidXmlConvertor.kt

fix: xml export idempotence

---

Readme/README.fr.md

added french language for better understanding

chore: Create README.fr.md

---

README.md

Corrected Grammar part to enhance the quality of reading

chore: Update README.md Corrected Grammar Part

---

.github/workflows/test.yml
backend/app/build.gradle
backend/testing/src/main/kotlin/io/tolgee/CleanDbTestListener.kt

chore: pipeline freeze during tests

---

.github/workflows/test.yml

chore: disable test report for pull requests from external repositories

---

README.md

I have made some corrections to your repository to help clarify certain aspects. These improvements aim to enhance the overall understanding and usability of the project. I hope they contribute positively to your work!

(typo):i've made some corrections to your documentation

---

webapp/src/views/projects/dashboard/ProjectTotals.tsx

[Closing](https://github.com/tolgee/management-other/issues/63)

fix: dashboard translations

---

backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/translation/TranslationsController.kt
backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/translations/v2TranslationsController/TranslationsControllerViewTest.kt
backend/data/src/main/kotlin/io/tolgee/development/testDataBuilder/data/TranslationsTestData.kt
backend/data/src/main/kotlin/io/tolgee/repository/TranslationRepository.kt
backend/data/src/main/kotlin/io/tolgee/service/translation/TranslationService.kt

feat: Provide filtering by key tags when getting all translations

---

webapp/src/views/projects/translations/CellKey.tsx
webapp/src/views/projects/translations/context/TranslationsContext.ts
webapp/src/views/projects/translations/context/services/useSelectionService.tsx

Closes #2713
https://github.com/tolgee/documentation/pull/761

feat: select multiple keys with holding shift key

---

backend/app/src/main/kotlin/io/tolgee/configuration/PortAvailability.kt

It gave just a cryptic error before, hard to determine what to do.
Closes #2648.

chore: Check port availability before starting Tomcat

---

webapp/src/ee/billing/administration/components/CloudPlanForm.tsx
webapp/src/ee/billing/administration/components/EePlanForm.tsx

Closes https://github.com/tolgee/billing/issues/71
Closes https://github.com/tolgee/billing/issues/63

chore: billing plans administration improvements

---

backend/data/src/main/resources/db/changelog/schema.xml

fix: set default value for new column in sso migrations

---

backend/app/src/test/kotlin/io/tolgee/api/v2/controllers/v2ImportController/SingleStepImportControllerTest.kt
backend/app/src/test/resources/import/po/codeReferences.po
backend/data/src/main/kotlin/io/tolgee/service/dataImport/StoredDataImporter.kt

FIxes [tolgee-cli#97](https://github.com/tolgee/tolgee-cli/issues/97)

fix: save code references before key metas to workaround hibernate bug

---

backend/app/src/test/kotlin/io/tolgee/websocket/AbstractWebsocketTest.kt

It does the same thing, just a bit shorter.

chore: Make asserts of websocket tests more concise

---

backend/api/src/main/kotlin/io/tolgee/api/v2/controllers/notification/NotificationController.kt
backend/api/src/main/kotlin/io/tolgee/hateoas/notification/NotificationWebsocketModel.kt
backend/app/src/test/kotlin/io/tolgee/websocket/AbstractWebsocketTest.kt
backend/data/src/main/kotlin/io/tolgee/events/OnNotificationsChangedForUser.kt
backend/data/src/main/kotlin/io/tolgee/repository/NotificationRepository.kt
backend/data/src/main/kotlin/io/tolgee/service/notification/NotificationService.kt
backend/data/src/main/kotlin/io/tolgee/websocket/WebsocketEventPublisher.kt
e2e/cypress/common/notifications.ts
e2e/cypress/e2e/tasks/tasksNotifications.cy.ts
e2e/cypress/support/dataCyType.d.ts
webapp/src/component/layout/TopBar/Notifications.tsx
webapp/src/websocket-client/WebsocketClient.ts

* Sending new notification in websocket instead of just ping.
* Not loading notifications before first opening of the notification list.

feat: Websockets optimizations for notifications

---

webapp/src/component/layout/Notifications/MfaDisabledItem.tsx
webapp/src/component/layout/Notifications/MfaEnabledItem.tsx
webapp/src/component/layout/Notifications/NotificationItem.tsx
webapp/src/component/layout/Notifications/NotificationTypeMap.tsx
webapp/src/component/layout/Notifications/NotificationsPopup.tsx
webapp/src/component/layout/Notifications/NotificationsTopBarButton.tsx
webapp/src/component/layout/Notifications/PasswordChangedItem.tsx
webapp/src/component/layout/Notifications/TaskAssignedItem.tsx
webapp/src/component/layout/Notifications/TaskCompletedItem.tsx
webapp/src/constants/links.tsx
webapp/src/ee/task/components/BoardItem.tsx
webapp/src/ee/task/components/TaskDetail.tsx
webapp/src/ee/task/components/TaskId.tsx
webapp/src/ee/task/components/TaskItem.tsx
webapp/src/ee/task/components/TaskReference.tsx
webapp/src/ee/task/components/TaskTooltip.tsx
webapp/src/ee/task/components/utils.ts

chore: Styling fixes from #2874

---

backend/app/build.gradle
backend/data/build.gradle

Alternative to #2920 and #2921

fix: update netty dependency

---

webapp/src/component/LimitedHeightText.tsx

https://github.com/user-attachments/assets/b829ef5e-a6ac-4bb4-ae8e-85fbd9bc3a37
/claim #2924
/closes #2924

fix: Adjust height threshold for Firefox compatibility

---

webapp/src/component/activity/types/getBatchLanguageIdsChange.tsx

Closes https://github.com/tolgee/tolgee-platform/issues/2891

fix: many language references in activity

---

backend/api/src/main/kotlin/io/tolgee/api/publicConfiguration/PublicConfigurationAssembler.kt
backend/api/src/main/kotlin/io/tolgee/api/publicConfiguration/PublicConfigurationDTO.kt
backend/data/src/main/kotlin/io/tolgee/configuration/tolgee/TolgeeProperties.kt
e2e/cypress/common/apiCalls/common.ts
e2e/cypress/common/shared.ts
e2e/cypress/e2e/translations/translationFilters.cy.ts
webapp/src/service/apiSchema.generated.ts
webapp/src/views/projects/translations/context/services/useTranslationsService.tsx

Closes: https://github.com/tolgee/tolgee-platform/issues/2907

feat: Configurable selected languages limit

---

e2e/cypress/e2e/administration/customerDebug.cy.ts
webapp/src/globalContext/useWsClientService.tsx
webapp/src/websocket-client/WebsocketClient.ts

fix: avoid subscribing to ws channel while ws is disconnecting
